version: '2'
services:
  peer1.takeda.tryme4u.com:
    container_name: peer1.takeda.tryme4u.com
    image: hyperledger/fabric-peer:$ARCH-1.1.0
    extra_hosts:
      - "orderer.tryme4u.com:10.0.0.8"
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.takeda.tryme4u.com
      - CORE_PEER_ADDRESS=peer1.takeda.tryme4u.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=TakedaMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/takeda.tryme4u.com/peers/peer1.takeda.tryme4u.com/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/takeda.tryme4u.com/users:/etc/hyperledger/msp/users
    depends_on:
      - couchdb1
  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:$ARCH-0.4.6
    ports:
      - 6984:5984
    environment:
      DB_URL: http://localhost:6984/member_db
